### PR TITLE
Add Leetcode question of JAVA with proper link and solution

### PR DESCRIPTION
**Pull request by Suryansh1720001**

### CODE REVIEW

**Comment by Suryansh1720001** [comment]
Hello @Lonewolf0502
Please review this PR and merge it accordingly. In this proper question, a link and solution is provided.
Thank you

**Comment by Lonewolf0502** [comment]
pls give proper description and follow rules(fork+star+follow)

**Comment by Suryansh1720001** [comment]
what do you mean by proper description?
I added the platform question link and a solution.

**Comment by Lonewolf0502** [comment]
proper description means tell what the problem is and solution(which u gave) not link

**Comment by markandey007** [comment]
@Lonewolf0502 bhai accept bhi krle laundo ka

**Comment by Lonewolf0502** [comment]
isko chatbox mat bna de

**Comment by Lonewolf0502** [comment]
@Suryansh1720001 will merge soon

**Pull request merged**
