### PR TITLE
LeetCode 234: Find palindrome Linked List

### PR DESCRIPTION
**Pull request by Sushant-1999**

### CODE REVIEW

**Comment by Sushant-1999** [comment]
@adidubs  please merge PR for hacktoberfest

**Comment by Lonewolf0502** [comment]
do follow rules fork follow and star repo

**Comment by Sushant-1999** [comment]
@Lonewolf0502 Done. Please merge now Bro!

**Comment by Lonewolf0502** [comment]
pls add proper description

**Comment by Sushant-1999** [comment]
Description : 
Given a singly linked list of characters, write a function that returns true if the given list is a palindrome, else false.
The idea is to use a stack and push all the nodes into the stack, then again iterate over the linked list to validate if the linked list is palindrome or not.
Follow the steps below to solve the problem:

A simple solution is to use a stack of list nodes. This mainly involves three steps.
Traverse the given list from head to tail and push every visited node to stack.
Traverse the list again. For every visited node, pop a node from the stack and compare data of popped node with the currently visited node.
If all nodes matched, then return true, else false.

@Lonewolf0502

**Comment by Sushant-1999** [comment]
Added Description @Lonewolf0502

**Comment by dubeyadi** [comment]
> @adidubs please merge PR for hacktoberfest

Please follow the Description given by @Lonewolf0502

**Comment by adidubs** [comment]
> @adidubs please merge PR for hacktoberfest
Please follow the Description given by @Lonewolf0502

**Pull request merged**
