### PR TITLE
Create TrappingRainWater.cpp

### PR DESCRIPTION
**Pull request by vrintle**
Added solution for LeetCode Hard problem: https://leetcode.com/problems/trapping-rain-water/

### CODE REVIEW

**Comment by vrintle** [comment]
Hey Raghavarya2002, I am Rahul Verma, a third year B. Tech. student from DTU. I am a competitive programmer (2000+ on Codeforces and 2200+ on CodeChef), you can check about me more on LinkedIn (ID: vrintle)

**Comment by Lonewolf0502** [comment]
pls give proper description about problem

**Comment by vrintle** [comment]
> pls give proper description about problem

Please check the updated pr

**Comment by Lonewolf0502** [comment]
pls merge all in single file and i will commit it

**Comment by Lonewolf0502** [comment]
good effort

**Pull request merged**
